'use client';

import { useState } from 'react';
import { createContinuityBible } from '@/lib/continuity/continuity-bible';
import AskAiDirectorButton from '@/components/AskAiDirectorButton';

export default function ContinuityBibleEditor({ value, onChange }) {
  const [bible, setBible] = useState(() => ({ ...createContinuityBible(), ...value }));
  function updateStyle(field, next) { const updated = { ...bible, projectVisualStyle: { ...bible.projectVisualStyle, [field]: next } }; setBible(updated); onChange?.(updated); }
  function addCharacter() { const character = { id: `character-${Date.now()}`, name: 'New character', role: 'Lead', identityLock: true, physicalTraits: '', hairAndMakeup: '', behaviorAndExpression: '', voiceOrPerformanceNotes: '', references: [], wardrobeLooks: [], doNotChange: [], allowedChanges: [] }; const updated = { ...bible, characters: [...bible.characters, character] }; setBible(updated); onChange?.(updated); }
  return <section className="cinex-continuity-bible" aria-labelledby="continuity-bible-title"><p className="cinex-shot-plan-eyebrow">Continuity Bible</p><h2 id="continuity-bible-title">Lock the details that make every scene feel like one seamless production.</h2><div className="cinex-continuity-section"><h3>Visual style</h3><p>Lock the look once so later shots have a dependable starting point.</p><label>Color palette<input value={bible.projectVisualStyle.colorPalette} onChange={(e) => updateStyle('colorPalette', e.target.value)} /></label><label>Camera language<input value={bible.projectVisualStyle.cameraLanguage} onChange={(e) => updateStyle('cameraLanguage', e.target.value)} /></label><label>Aspect ratio<input value={bible.projectVisualStyle.aspectRatio} onChange={(e) => updateStyle('aspectRatio', e.target.value)} /></label><AskAiDirectorButton fieldType="visualNotes" value={bible.projectVisualStyle.cameraLanguage} context={{ style: bible.projectVisualStyle.cameraLanguage }} onApply={(suggestion) => updateStyle('cameraLanguage', suggestion)} /></div><div className="cinex-continuity-section"><h3>Characters</h3><p>Lock identity, behavior, and intentional changes.</p>{bible.characters.map((character, index) => <label key={character.id}>Character {index + 1}<input value={character.name} onChange={(e) => { const characters = bible.characters.map((item, itemIndex) => itemIndex === index ? { ...item, name: e.target.value } : item); const updated = { ...bible, characters }; setBible(updated); onChange?.(updated); }} /></label>)}<button type="button" className="cinex-auth-secondary" onClick={addCharacter}>Add character</button></div><div className="cinex-continuity-section"><h3>Global do-not-change rules</h3><p>Write the constraints that protect the project’s identity.</p><textarea value={(bible.globalRules || []).join('\n')} onChange={(e) => { const updated = { ...bible, globalRules: e.target.value.split('\n').filter(Boolean) }; setBible(updated); onChange?.(updated); }} rows={4} /></div></section>;
}
